"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard_jobs_list from './dashboard-jobs-list.bones.json'
import _workspace_telemetry_overview from './workspace-telemetry-overview.bones.json'

registerBones({
  "dashboard-jobs-list": _dashboard_jobs_list,
  "workspace-telemetry-overview": _workspace_telemetry_overview,
})
